### ISSUE TITLE
Bot geliştirmesi içinbir kaç öneri

### ISSUE THREAD

**Issue by delidolu1adam** [RFKaya/Nraphy#18]
Merhaba, ilk defa bu kadar teferruatlı bir bot gördüm. Geliştirmeye açık olması ayrı bir güzel.

1: Çoklu dil desteği
2: Müzik çalar için buton desteği
3: Müzik çalar için arayüz tasarımı
4: Müzik çalar için arama özelliği, örneğin Sagopa yazdığımda sagopa ile en popüler 10 içeriği hemen göstersin ve seçilebilsin.

Son olarak komutlarda "Çal" yerine "Oynat" kullanmanız çok daha doğru olur diye düşünüyorum. Teşekkürler.

Arayüz için örnek görsel tasarım.
![discord_music_bot_play_interface](https://github.com/RFKaya/Nraphy/assets/6446405/c01b210f-8573-42db-97bd-d4f5c5c083d5)

**Comment by RFKaya** [comment]
Birinci, ikinci ve üçüncü madde için Branch oluşturup kodları yazmamızda yardımcı olursan çok makbule geçer.
4. madde ise hâli hazırda var. Müzik komutları sayfasından görebilirsin. 
Çal yerine oynat'ı en başta yapmamız gerekirdi. Şu an değiştirmeye kalkışırsak kullanıcılar için zahmet çıkarmış oluruz.

Önerin için teşekkürler ❤️
