### ISSUE TITLE
Bot ne zaman güncellenecek

### ISSUE THREAD

**Issue by IceDragonOfficial** [RFKaya/Nraphy#20]
Merhaba kaya, bu botun github'ını ne zaman güncelleyeceksin ?

**Comment by RFKaya** [comment]
Yakın gelecekte değil. Daha vakit var.

**Comment by IceDragonOfficial** [comment]
tamamdır hocam

**Comment by IceDragonOfficial** [comment]
ekonomi çok iyi botun o yüzden sorayım dedim ^^
